### ISSUE TITLE
Issues with running `ppo_multidiscrete.py`

### ISSUE THREAD

**Issue by luckyShaw** [vwxyzjn/PPO-Implementation-Deep-Dive#3]
![image](https://user-images.githubusercontent.com/65491120/145535437-02185553-de3c-4ed1-98ee-0e03f1b53687.png)

**Comment by vwxyzjn** [comment]
Try poetry install -E gym-microrts

**Comment by luckyShaw** [comment]
![image](https://user-images.githubusercontent.com/65491120/145675600-abb59037-75b3-403a-82fd-a38684ca5f8e.png)
I tried then I got this error. Is poetry indispensable?

**Comment by vwxyzjn** [comment]
It’s not. I think it’s because windows require PyTorch wheels not found in PyPi. Feel free to install however you want.

**Comment by luckyShaw** [comment]
![image](https://user-images.githubusercontent.com/65491120/145716222-50e110b5-4a70-4c61-897d-67a30c59d051.png)
![image](https://user-images.githubusercontent.com/65491120/145716231-d1b6f572-45f1-4984-a13b-5c8265d21052.png)
I found this part is different from paper, is it an erro or you intended to do that.

**Comment by vwxyzjn** [comment]
Why is it different? `c1` corresponds to `args.vf_coef` and `c2` corresponds to `args.ent_coef`. The signs are reversed because you maximize the expectation in the formula, whereas in the code, you minimize the loss.

**Comment by vwxyzjn** [comment]
Also, just to confirm. Are you able to run `ppo_multidiscrete.py` successfully?

**Comment by luckyShaw** [comment]
No, I tried, but kept getting environment not found error. Then I directly read the code. Sorry, I missed that the pg_loss is also reversed.

**Comment by vwxyzjn** [comment]
Here is a complete walk through https://asciinema.org/a/GeYz256XrAh6qH6IQQqE66cod

**Comment by luckyShaw** [comment]
Thanks
